### ISSUE TITLE
"version" goal not working for multi-module project

### ISSUE THREAD

**Issue by janzyka** [smartcodeltd/release-candidate-maven-plugin#9]
When you have multi-module project where the submodule only has `<parent>` so it inherits it's version running `mvn release-candidate:version` in parent project results in following error:

```
[ERROR] Failed to execute goal com.smartcodeltd:release-candidate-maven-plugin:1.0.0-201601120029.6e3772b:version (default-cli) on project submodule: Couldn't read project version from '/path/projectRoot/submodule/pom.xml'. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.smartcodeltd:release-candidate-maven-plugin:1.0.0-201601120029.6e3772b:version (default-cli) on project xxx: Couldn't read project version from '/path/projectRoot/submodule/pom.xml'.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Couldn't read project version from '/path/projectRoot/submodule/pom.xml'.
    at com.smartcodeltd.VersionMojo.execute(VersionMojo.java:89)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 20 more
Caused by: java.lang.NullPointerException
    at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:210)
    at com.smartcodeltd.VersionMojo.currentVersionFrom(VersionMojo.java:94)
    at com.smartcodeltd.VersionMojo.execute(VersionMojo.java:81)
    ... 22 more
```

**Comment by jan-molak** [comment]
Hi and thanks for the feedback @janzyka. Would you mind raising a PR with example poms so that I can reproduce the issue?

Have a look at the [existing integration tests](https://github.com/smartcodeltd/release-candidate-maven-plugin/tree/master/src/it/) and just add one that covers this scenario please.

Many thanks for your time and help.
Jan

**Comment by janzyka** [comment]
On pull request
